import { Room } from "@/lib/store";

export const buildTestRoom = (state: Room["state"] = "voting"): Room => ({
    id: "TEST",
    mode: "multiplayer",
    name: "Sala de prueba",
    intensity: "medio",
    duration: "corta",
    topicConfig: {
        mode: "system",
        selectedCategories: [],
        selectedIntensities: ["media"],
        customTopics: [],
        mixStrategy: "balanced",
    },
    topicSelectionMode: "automatic",
    state,
    hostId: "host-1",
    players: [
        { id: "host-1", name: "Ana", role: "debatiente_a", isHost: true, score: 0, wins: 0 },
        { id: "player-2", name: "Beto", role: "debatiente_b", isHost: false, score: 0, wins: 0 },
        { id: "player-3", name: "Cata", role: "jurado", isHost: false, score: 0, wins: 0 },
        { id: "player-4", name: "Dani", role: "jurado", isHost: false, score: 0, wins: 0 },
    ],
    rounds: [{
        number: 1,
        topicId: "m1",
        topic: null,
        roundTopic: "random",
        selectedTopic: "m1",
        debatienteA_Id: "host-1",
        debatienteB_Id: "player-2",
        timeRemainingA: 0,
        timeRemainingB: 0,
        debateState: "finished",
        activeSpeaker: "debatiente_a",
        transitionRemaining: 0,
        turnStartTime: null,
        votes: { "player-3": "host-1", "player-4": "player-2" },
        secondaryVotes: { "player-3": "Fue mas claro", "player-4": "Respondio mejor" },
        resolutionVotes: {},
        fallaciesSignaled: [],
        activeChallenge: null,
        winnerId: null,
    }],
    currentRoundIndex: 0,
    usedTopics: ["m1"],
    savedTopics: [{
        id: "saved-1",
        text: "Tema privado del host",
        createdAt: Date.now(),
        source: "user",
    }],
    createdAt: Date.now(),
});
